#player level handler
variables:
	{db_level.%player%} = 0

every 5 seconds:
	loop all players:
		#player level notifier
		
		#level 0 (only here to set the variable)
		{level.%loop-player%} is less than 1500:
			set {level.%loop-player%.actual} to 0
		
		#lvl 1
		{level.%loop-player%} is greater than or equal to 1500:
			#broadcast detection to avoid extra alerts (found out the hard way
			#that this was needed)
			{level.%loop-player%.actual} is 0:
				set {level.%loop-player%.actual} to 1
				broadcast "&a&l%loop-player% is now Level 1!"
				add 100 to loop-player's balance
				send "&aYou have been given 100 tickets for reaching Level 1!" to loop-player
				
		#lvl 2
		{level.%loop-player%} is greater than or equal to 3000:
			#broadcast detection to avoid extra alerts (found out the hard way
			#that this was needed)
			{level.%loop-player%.actual} is 1:
				set {level.%loop-player%.actual} to 2
				broadcast "&a&l%loop-player% is now Level 2!"
				add 100 to loop-player's balance
				send "&aYou have been given 100 tickets for reaching Level 2!" to loop-player
				
		#lvl 3
		{level.%loop-player%} is greater than or equal to 4500:
			#broadcast detection to avoid extra alerts (found out the hard way
			#that this was needed)
			{level.%loop-player%.actual} is 2:
				set {level.%loop-player%.actual} to 3
				broadcast "&a&l%loop-player% is now Level 3!"
				add 100 to loop-player's balance
				send "&aYou have been given 100 tickets for reaching Level 3!" to loop-player
				
		#lvl 4
		{level.%loop-player%} is greater than or equal to 6000:
			#broadcast detection to avoid extra alerts (found out the hard way
			#that this was needed)
			{level.%loop-player%.actual} is 3:
				set {level.%loop-player%.actual} to 4
				broadcast "&a&l%loop-player% is now Level 4!"
				add 100 to loop-player's balance
				send "&aYou have been given 100 tickets for reaching Level 4!" to loop-player
				
		#lvl 5
		{level.%loop-player%} is greater than or equal to 7500:
			{level.%loop-player%.actual} is 4:
				set {level.%loop-player%.actual} to 5
				broadcast "&a&l%loop-player% is now level 5!"
				add 100 to loop-player's balance
				send "&aYou have been given 100 tickets for reaching Level 5!" to loop-player
				
		#lvl 6
		{level.%loop-player%} is greater than or equal to 9000:
			{level.%loop-player%.actual} is 5:
				set {level.%loop-player%.actual} to 6
				broadcast "&a&l%loop-player% is now level 6!"
				add 100 to loop-player's balance
				send "&aYou have been given 100 tickets for reaching Level 6!" to loop-player
				
		#lvl 7
		{level.%loop-player%} is greater than or equal to 10500:
			{level.%loop-player%.actual} is 6:
				set {level.%loop-player%.actual} to 7
				broadcast "&a&l%loop-player% is now level 7!"
				add 100 to loop-player's balance
				send "&aYou have been given 100 tickets for reaching Level 7!" to loop-player
				
		#lvl 8
		{level.%loop-player%} is greater than or equal to 12000:
			{level.%loop-player%.actual} is 7:
				set {level.%loop-player%.actual} to 8
				broadcast "&a&l%loop-player% is now level 8!"
				add 100 to loop-player's balance
				send "&aYou have been given 100 tickets for reaching Level 8!" to loop-player
				
				
		#lvl 9
		{level.%loop-player%} is greater than or equal to 13500:
			{level.%loop-player%.actual} is 8:
				set {level.%loop-player%.actual} to 9
				broadcast "&a&l%loop-player% is now level 9!"
				add 100 to loop-player's balance
				send "&aYou have been given 100 tickets for reaching Level 9!" to loop-player
				
				
		#lvl 10
		{level.%loop-player%} is greater than or equal to 15000:
			{level.%loop-player%.actual} is 9:
				set {level.%loop-player%.actual} to 10
				broadcast "&a&l%loop-player% is now level 10!"
				add 100 to loop-player's balance
				send "&aYou have been given 100 tickets for reaching Level 10!" to loop-player
				
				
		#lvl 11
		{level.%loop-player%} is greater than or equal to 16500:
			{level.%loop-player%.actual} is 10:
				set {level.%loop-player%.actual} to 11
				broadcast "&a&l%loop-player% is now level 11!"
				add 100 to loop-player's balance
				send "&aYou have been given 100 tickets for reaching Level 11!" to loop-player
				
				
		#lvl 12
		{level.%loop-player%} is greater than or equal to 18000:
			{level.%loop-player%.actual} is 11:
				set {level.%loop-player%.actual} to 12
				broadcast "&a&l%loop-player% is now level 12!"
				add 100 to loop-player's balance
				send "&aYou have been given 100 tickets for reaching Level 12!" to loop-player
				
				
		#lvl 13
		{level.%loop-player%} is greater than or equal to 19500:
			{level.%loop-player%.actual} is 12:
				set {level.%loop-player%.actual} to 13
				broadcast "&a&l%loop-player% is now level 13!"
				add 100 to loop-player's balance
				send "&aYou have been given 100 tickets for reaching Level 13!" to loop-player
				
				
		#lvl 14
		{level.%loop-player%} is greater than or equal to 21000:
			{level.%loop-player%.actual} is 13:
				set {level.%loop-player%.actual} to 14
				broadcast "&a&l%loop-player% is now level 14!"
				add 100 to loop-player's balance
				send "&aYou have been given 100 tickets for reaching Level 14!" to loop-player
				
				
		#lvl 15
		{level.%loop-player%} is greater than or equal to 22500:
			{level.%loop-player%.actual} is 14:
				set {level.%loop-player%.actual} to 15
				broadcast "&a&l%loop-player% is now level 15!"
				add 100 to loop-player's balance
				send "&aYou have been given 100 tickets for reaching Level 15!" to loop-player
				

		#lvl 16
		{level.%loop-player%} is greater than or equal to 24000:
			{level.%loop-player%.actual} is 15:
				set {level.%loop-player%.actual} to 16
				broadcast "&a&l%loop-player% is now level 16!"
				add 100 to loop-player's balance
				send "&aYou have been given 100 tickets for reaching Level 16!" to loop-player
				
				
		#lvl 17
		{level.%loop-player%} is greater than or equal to 25500:
			{level.%loop-player%.actual} is 16:
				set {level.%loop-player%.actual} to 17
				broadcast "&a&l%loop-player% is now level 17!"
				add 100 to loop-player's balance
				send "&aYou have been given 100 tickets for reaching Level 17!" to loop-player
				
				
		#lvl 18
		{level.%loop-player%} is greater than or equal to 27000:
			{level.%loop-player%.actual} is 17:
				set {level.%loop-player%.actual} to 18
				broadcast "&a&l%loop-player% is now level 18!"
				add 100 to loop-player's balance
				send "&aYou have been given 100 tickets for reaching Level 18!" to loop-player
				
				
		#lvl 19
		{level.%loop-player%} is greater than or equal to 28500:
			{level.%loop-player%.actual} is 18:
				set {level.%loop-player%.actual} to 19
				broadcast "&a&l%loop-player% is now level 19!"
				add 100 to loop-player's balance
				send "&aYou have been given 100 tickets for reaching Level 19!" to loop-player
				
				
		#lvl 20
		{level.%loop-player%} is greater than or equal to 30000:
			{level.%loop-player%.actual} is 19:
				set {level.%loop-player%.actual} to 20
				broadcast "&a&l%loop-player% is now level 20!"
				add 100 to loop-player's balance
				send "&aYou have been given 100 tickets for reaching Level 20!" to loop-player
		
		set {db_level.%loop-player%} to {level.%loop-player%}
		set {db_level.%loop-player%.actual} to {level.%loop-player%.actual}
		
		
on join:
	{db_level.%player%} is set:
		set {level.%player%} to {db_level.%player%}
		set {level.%player%.actual} to {db_level.%player%.actual}
			
			
			
			
			
			
#adminGivelevelcommand

command /lvlg <player> <number>:
	description: gives players levels
	permission: obam.admin.lvl
	usage: /lvlg <Player Name> <Level Number>
	trigger:
		argument 2 is 0:
			set {level.%player-argument%} to 0
			set {level.%player-argument%.actual} to 0
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop
		argument 2 is 1:
			set {level.%player-argument%} to 1500
			set {level.%player-argument%.actual} to argument 2 - 1
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop
		argument 2 is 2:
			set {level.%player-argument%} to 3000
			set {level.%player-argument%.actual} to argument 2 - 1
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop
		argument 2 is 3:
			set {level.%player-argument%} to 4500
			set {level.%player-argument%.actual} to argument 2 - 1
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop
		argument 2 is 4:
			set {level.%player-argument%} to 6000
			set {level.%player-argument%.actual} to argument 2 - 1
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop
		argument 2 is 5:
			set {level.%player-argument%} to 7500
			set {level.%player-argument%.actual} to argument 2 - 1
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop
		argument 2 is 6:
			set {level.%player-argument%} to 9000
			set {level.%player-argument%.actual} to argument 2 - 1
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop
		argument 2 is 7:
			set {level.%player-argument%} to 10500
			set {level.%player-argument%.actual} to argument 2 - 1
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop
		argument 2 is 8:
			set {level.%player-argument%} to 12000
			set {level.%player-argument%.actual} to argument 2 - 1
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop
		argument 2 is 9:
			set {level.%player-argument%} to 13500
			set {level.%player-argument%.actual} to argument 2 - 1
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop
		argument 2 is 10:
			set {level.%player-argument%} to 15000
			set {level.%player-argument%.actual} to argument 2 - 1
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop
		argument 2 is 11:
			set {level.%player-argument%} to 16500
			set {level.%player-argument%.actual} to argument 2 - 1
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop
		argument 2 is 12:
			set {level.%player-argument%} to 18000
			set {level.%player-argument%.actual} to argument 2 - 1
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop
		argument 2 is 13:
			set {level.%player-argument%} to 19500
			set {level.%player-argument%.actual} to argument 2 - 1
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop
		argument 2 is 14:
			set {level.%player-argument%} to 21000
			set {level.%player-argument%.actual} to argument 2 - 1
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop
		argument 2 is 15:
			set {level.%player-argument%} to 22500
			set {level.%player-argument%.actual} to argument 2 - 1
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop
		argument 2 is 16:
			set {level.%player-argument%} to 24000
			set {level.%player-argument%.actual} to argument 2 - 1
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop
		argument 2 is 17:
			set {level.%player-argument%} to 25500
			set {level.%player-argument%.actual} to argument 2 - 1
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop
		argument 2 is 18:
			set {level.%player-argument%} to 27000
			set {level.%player-argument%.actual} to argument 2 - 1
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop
		argument 2 is 19:
			set {level.%player-argument%} to 28500
			set {level.%player-argument%.actual} to argument 2 - 1
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop
		argument 2 is 20:
			set {level.%player-argument%} to 30000
			set {level.%player-argument%.actual} to argument 2 - 1
			send "&aYou have been set to level %argument 2% by %player%" to player-argument
			stop

#levelcheck command
command /lvlc <offline player>:
	description: debug for levels
	usage: /lvlc <player>
	permission: obam.level.admin
	trigger:
		send "%offline player-argument%'s level is %{db_level.%offline player-argument%.actual}%" to player
		send "%offline player-argument%'s level score is %{db_level.%offline player-argument%}%" to player

#level command for players
command /level:
	description: Displays level
	usage: level
	permission: obam.level.user
	trigger:
		send "&aYour level is &a&l%{db_level.%player%.actual}%&a!" to player
		{db_level.%player%.actual} is 20:
			send "&a[&e██████████&a]" to player
			stop
			
		send "&cProgress to next level:"
		set {displaylevelcount} to "%{db_level.%player%} / 1500%"
		set {level.display.%player%::*} to {displaylevelcount} parsed as "%number%.%number%"
		{level.display.%player%::2} is less than 10:
			set {level.display.%player%.board} to "&a[&8██████████&a]"
		{level.display.%player%::2} is greater than or equal to 10:
			{level.display.%player%::2} is less than 20:
				set {level.display.%player%.board} to "&a[&e█&8████████&a]"
		{level.display.%player%::2} is greater than or equal to 20:
			{level.display.%player%::2} is less than 30:
				set {level.display.%player%.board} to "&a[&e██&8███████&a]"
		{level.display.%player%::2} is greater than or equal to 30:
			{level.display.%player%::2} is less than 40:
				set {level.display.%player%.board} to "&a[&e███&8██████&a]"
		{level.display.%player%::2} is greater than or equal to 40:
			{level.display.%player%::2} is less than 50:
				set {level.display.%player%.board} to "&a[&e████&8█████&a]"
		{level.display.%player%::2} is greater than or equal to 50:
			{level.display.%player%::2} is less than 60:
				set {level.display.%player%.board} to "&a[&e█████&8████&a]"
		{level.display.%player%::2} is greater than or equal to 60:
			{level.display.%player%::2} is less than 70:
				set {level.display.%player%.board} to "&a[&e██████&8███&a]"
		{level.display.%player%::2} is greater than or equal to 70:
			{level.display.%player%::2} is less than 80:
				set {level.display.%player%.board} to "&a[&e███████&8██&a]"
		{level.display.%player%::2} is greater than or equal to 80:
			{level.display.%player%::2} is less than 90:
				set {level.display.%player%.board} to "&a[&e████████&8██&a]"
		{level.display.%player%::2} is greater than or equal to 90:
			set {level.display.%player%.board} to "&a[&e█████████&8█&a]"
		{level.display.%player%::2} is not set:
			set {level.display.%player%.board} to "&a[&8██████████&a]"
		{level.display.%player%::2} is 1:
			set {level.display.%player%.board} to "&a[&e█&8████████&a]"
		{level.display.%player%::2} is 2:
			set {level.display.%player%.board} to "&a[&e██&8███████&a]"
		{level.display.%player%::2} is 3:
			set {level.display.%player%.board} to "&a[&e███&8██████&a]"
		{level.display.%player%::2} is 4:
			set {level.display.%player%.board} to "&a[&e████&8█████&a]"
		{level.display.%player%::2} is 5:
			set {level.display.%player%.board} to "&a[&e█████&8████&a]"
		{level.display.%player%::2} is 6:
			set {level.display.%player%.board} to "&a[&e██████&8███&a]"
		{level.display.%player%::2} is 7:
			set {level.display.%player%.board} to "&a[&e███████&8██&a]"
		{level.display.%player%::2} is 8:
			set {level.display.%player%.board} to "&a[&e████████&8██&a]"
		{level.display.%player%::2} is 9:
			set {level.display.%player%.board} to "&a[&e█████████&8█&a]"
		send "%{level.display.%player%.board}%" to player
		clear {level.display.%player%::*}
			
command /lvlscg <player> <number>:
	trigger:
		add arg 2 to {level.%player-argument%}
		
command /levellist:
	trigger:
		loop all players:
			#startfold @levelcheck
			{level.list.1} is not set:
				set {level.list.1} to {level.%loop-player%}
				set {level.list.1.name} to loop-player
				stop
			{level.%loop-player%} is greater than {level.list.1}:
				set {level.list.10} to {level.list.9}
				set {level.list.10.name} to {level.list.9.name}
				set {level.list.9} to {level.list.8}
				set {level.list.9.name} to {level.list.9.name}
				set {level.list.8} to {level.list.7}
				set {level.list.8.name} to {level.list.7.name}
				set {level.list.7} to {level.list.6}
				set {level.list.7.name} to {level.list.6.name}
				set {level.list.6} to {level.list.5}
				set {level.list.6.name} to {level.list.5.name}
				set {level.list.5} to {level.list.4}
				set {level.list.5.name} to {level.list.4.name}
				set {level.list.4} to {level.list.3}
				set {level.list.4.name} to {level.list.3.name}
				set {level.list.3} to {level.list.2}
				set {level.list.3.name} to {level.list.2.name}
				set {level.list.2} to {level.list.1}
				set {level.list.2.name} to {level.list.1.name}
				set {level.list.1} to {level.%loop-player%}
				set {level.list.1.name} to loop-player
				stop
			{level.list.2} is not set:
				set {level.list.2} to {level.%loop-player%}
				set {level.list.2.name} to loop-player
				stop
			{level.%loop-player%} is greater than {level.list.2}:
				set {level.list.10} to {level.list.9}
				set {level.list.10.name} to {level.list.9.name}
				set {level.list.9} to {level.list.8}
				set {level.list.9.name} to {level.list.9.name}
				set {level.list.8} to {level.list.7}
				set {level.list.8.name} to {level.list.7.name}
				set {level.list.7} to {level.list.6}
				set {level.list.7.name} to {level.list.6.name}
				set {level.list.6} to {level.list.5}
				set {level.list.6.name} to {level.list.5.name}
				set {level.list.5} to {level.list.4}
				set {level.list.5.name} to {level.list.4.name}
				set {level.list.4} to {level.list.3}
				set {level.list.4.name} to {level.list.3.name}
				set {level.list.3} to {level.list.2}
				set {level.list.3.name} to {level.list.2.name}
				set {level.list.2} to {level.%loop-player%}
				set {level.list.2.name} to loop-player
				stop
			{level.list.3} is not set:
				set {level.list.3} to {level.%loop-player%}
				set {level.list.3.name} to loop-player
				stop
			{level.%loop-player%} is greater than {level.list.3}:
				set {level.list.10} to {level.list.9}
				set {level.list.10.name} to {level.list.9.name}
				set {level.list.9} to {level.list.8}
				set {level.list.9.name} to {level.list.9.name}
				set {level.list.8} to {level.list.7}
				set {level.list.8.name} to {level.list.7.name}
				set {level.list.7} to {level.list.6}
				set {level.list.7.name} to {level.list.6.name}
				set {level.list.6} to {level.list.5}
				set {level.list.6.name} to {level.list.5.name}
				set {level.list.5} to {level.list.4}
				set {level.list.5.name} to {level.list.4.name}
				set {level.list.4} to {level.list.3}
				set {level.list.4.name} to {level.list.3.name}
				set {level.list.3} to {level.%loop-player%}
				set {level.list.3.name} to loop-player
				stop
			{level.list.4} is not set:
				set {level.list.4} to {level.%loop-player%}
				set {level.list.4.name} to loop-player
				stop
			{level.%loop-player%} is greater than {level.list.4}:
				set {level.list.10} to {level.list.9}
				set {level.list.10.name} to {level.list.9.name}
				set {level.list.9} to {level.list.8}
				set {level.list.9.name} to {level.list.9.name}
				set {level.list.8} to {level.list.7}
				set {level.list.8.name} to {level.list.7.name}
				set {level.list.7} to {level.list.6}
				set {level.list.7.name} to {level.list.6.name}
				set {level.list.6} to {level.list.5}
				set {level.list.6.name} to {level.list.5.name}
				set {level.list.5} to {level.list.4}
				set {level.list.5.name} to {level.list.4.name}
				set {level.list.4} to {level.%loop-player%}
				set {level.list.4.name} to loop-player
				stop
			{level.list.5} is not set:
				set {level.list.5} to {level.%loop-player%}
				set {level.list.5.name} to loop-player
				stop
			{level.%loop-player%} is greater than {level.list.5}:
				set {level.list.10} to {level.list.9}
				set {level.list.10.name} to {level.list.9.name}
				set {level.list.9} to {level.list.8}
				set {level.list.9.name} to {level.list.9.name}
				set {level.list.8} to {level.list.7}
				set {level.list.8.name} to {level.list.7.name}
				set {level.list.7} to {level.list.6}
				set {level.list.7.name} to {level.list.6.name}
				set {level.list.6} to {level.list.5}
				set {level.list.6.name} to {level.list.5.name}
				set {level.list.5} to {level.%loop-player%}
				set {level.list.5.name} to loop-player
				stop
			{level.list.6} is not set:
				set {level.list.6} to {level.%loop-player%}
				set {level.list.6.name} to loop-player
				stop
			{level.%loop-player%} is greater than {level.list.6}:
				set {level.list.10} to {level.list.9}
				set {level.list.10.name} to {level.list.9.name}
				set {level.list.9} to {level.list.8}
				set {level.list.9.name} to {level.list.9.name}
				set {level.list.8} to {level.list.7}
				set {level.list.8.name} to {level.list.7.name}
				set {level.list.7} to {level.list.6}
				set {level.list.7.name} to {level.list.6.name}
				set {level.list.6} to {level.%loop-player%}
				set {level.list.6.name} to loop-player
				stop
			{level.list.7} is not set:
				set {level.list.7} to {level.%loop-player%}
				set {level.list.7.name} to loop-player
				stop
			{level.%loop-player%} is greater than {level.list.7}:
				set {level.list.10} to {level.list.9}
				set {level.list.10.name} to {level.list.9.name}
				set {level.list.9} to {level.list.8}
				set {level.list.9.name} to {level.list.9.name}
				set {level.list.8} to {level.list.7}
				set {level.list.8.name} to {level.list.7.name}
				set {level.list.7} to {level.%loop-player%}
				set {level.list.7.name} to loop-player
				stop
			{level.list.8} is not set:
				set {level.list.8} to {level.%loop-player%}
				set {level.list.8.name} to loop-player
				stop
			{level.%loop-player%} is greater than {level.list.8}:
				set {level.list.10} to {level.list.9}
				set {level.list.10.name} to {level.list.9.name}
				set {level.list.9} to {level.list.8}
				set {level.list.9.name} to {level.list.9.name}
				set {level.list.8} to {level.%loop-player%}
				set {level.list.8.name} to loop-player
				stop
			{level.list.9} is not set:
				set {level.list.9} to {level.%loop-player%}
				set {level.list.9.name} to loop-player
				stop
			{level.%loop-player%} is greater than {level.list.9}:
				set {level.list.10} to {level.list.9}
				set {level.list.10.name} to {level.list.9.name}
				set {level.list.9} to {level.%loop-player%}
				set {level.list.9.name} to loop-player
				stop
			{level.list.10} is not set:
				set {level.list.10} to {level.%loop-player%}
				set {level.list.10.name} to loop-player
				stop
			{level.%loop-player%} is greater than {level.list.10}:
				set {level.list.10} to {level.%loop-player%}
				set {level.list.10.name} to loop-player
				stop
				#endfold
	

command /listme:
	trigger:
		{_count} is not set:
			set {_count} to 0
		while {_count} is less than 10:
			add 1 to {_count}
			set {_player} to {level.list.%{_count}%.name}
			send "&a%{_count}%. &e%{_player}%&a...........&e%{level.%{_player}%.actual}%" to player
			
			
				

			

		
		
		
		