command /alert <text>:
    description: Send serverwide alert
    usage: /alert <message>
    permission: obam.sendalert
    permission message: Command failed! You are not fluffy enough to send alerts!
    executable by: players, console
    trigger:
        broadcast "&5[ALERT]&d %arg 1%"
command /help:
    description: Shows help
    usage: /help
    executable by: players
    aliases: /is help
    trigger:
        send "&9----&b[&3 OBAM Skyblock Help &b]&9------------------------------" to player
        send "&3/start &b- Start an island if you don't already have one" to player
        send "&3/home &b- Go back to your island" to player
        send "&3/restart &b- Reset your island to default" to player
        send "&3/setspawn &b- Sets your island's spawnpoint as your location" to player
        send "&3/top10 &b- View the top 10 islands based on level" to player
        send "&3/warphelp &b- View how to use the warp system" to player
        send "&3/partyhelp &b- View how to use the party system" to player
command /warphelp:
    description: Shows help
    usage: /help
    executable by: players
    trigger:
        send "&9----&b[&3 OBAM Skyblock Help &b]&9------------------------------" to player
        send "&3/go [name] &b- Go to someone's island" to player
        send "&3/setwarp &b- Set where players /go to your island." to player
        send "&3/togglewarp &b- Control if people can /go to your island or not" to player
command /partyhelp:
    description: Shows help
    usage: /partyhelp
    executable by: players
    trigger:
        send "&9----&b[&3 OBAM Skyblock Help &b]&9------------------------------" to player
        send "&3/invite [name] &b- Invite someone to your island" to player
        send "&3/accept &b- Accept a party invite." to player
        send "&3/accept &b- Accept a party invite." to player
        send "&3/remove [name] &b- Remove a player from your party" to player
command /home:
    description: Go to island's home
    usage: /home or /start
    executable by: players
    aliases: /start
    trigger:
        make player execute command "/is"
command /restart:
    description: Restart your island
    usage: /restart
    executable by: players
    aliases: /reset
    trigger:
        make player execute command "/is restart"
command /setspawn:
    description: Sets island's spawnpoint
    usage: /spawnpoint while standing in location
    executable by: players
    aliases: /sethome
    trigger:
        make player execute command "/is sethome"
command /go <offline player>:
    description: Go to a player's island
    usage: /go [player name]
    executable by: players
    trigger:
        make player execute command "/is warp %arg 1%"
command /top10:
    description: See top 10 islands
    usage: /top10
    trigger:
        make player execute command "/is top"
command /allowfree <text>:
    usage: /allowfree [permission]
    trigger:
        make player execute command "/permissions group default set %arg 1%"
command /allowsupporter <text>:
    usage: /allowsupporter [permission]
    trigger:
        make player execute command "/permissions group supporter set %arg 1%"
command /allowplus <text>:
    usage: /allowsplus [permission]
    trigger:
        make player execute command "/permissions group plus set %arg 1%"
command /allowmod <text>:
    usage: /allowmod [permission]
    trigger:
        make player execute command "/permissions group moderator set %arg 1%"
command /allowsmod <text>:
    usage: /allowsmod [permission]
    trigger:
        make player execute command "/permissions group supermod set %arg 1%"
command /allowadmin <text>:
    usage: /allowadmin [permission]
    trigger:
        make player execute command "/permissions group admin set %arg 1%"
command /spawn:
    usage: /spawn
    permission: obam.skyblock.spawn
    trigger:
        world is "parkourmaps":
            make player execute command "/mvtp parkourlobby"
            set {fallen.%player%} to 0
            stop
        world is "parkourlobby":
            make player execute command "/mvtp parkourlobby"
            set {fallen.%player%} to 0
            stop
        make player execute command "/mv spawn"
command /setwarp <text>:
    description: Set warp location for island
    usage: /setwarp
    trigger:
        make player execute command "/is setwarp"
command /togglewarp:
    description: Toggle if other players can warp to your island
    usage: /togglewarp
    trigger:
        make player execute command "/is togglewarp"
command /invite <text>:
    description: Invite someone to your island
    usage: /invite [name]
    trigger:
        make player execute command "/is invite %arg 1%"
command /enchantment:
    permission: obam.skyblock.enchantment
    trigger:
        teleport the player to the location (-29, 122, 21)
command /colors:
    trigger:
        send "&11&22&33&44&55&66&77&88&99&aa&bb&cc&dd&ee&ff" to player
command /fixdifficulty:
    permission:obam.skyblock.fixdifficulty
    trigger:
        make player execute command "/mvm set monsters true skyworld"
        make player execute command "/mvm set difficulty 2 skyworld"
command /accept:
    description: Accept party invite
    usage: /accept
    trigger:
        make player execute command "/is accept"
command /reject:
    description: Reject party invite
    usage: /reject
    trigger:
        make player execute command "/is reject"
command /remove <text>:
    description: Remove a player from your island
    usage: /remove [name]
    trigger:
        make player execute command "/is kick %arg 1%"