#ticket stuff
command /settickettime:
	trigger:
		player is op
		set {ticket.tracker} to now
		
on join:
	wait 30 seconds
	{db_ticket.tracker.count.%player%} is not set:
		set {db_ticket.tracker.count.%player%} to {ticket.tracker.count.%player%}
	set {ticket.tracker.count.%player%} to {db_ticket.tracker.count.%player%}
	player has permission "obam.supporter.tickets":
		{ticket.tracker.count.%player%} is not set:
			set {ticket.tracker.count.%player%} to {ticket.tracker.count}
			{ticket.tracker.bonus.%player%} is not set:
				add 2000 to player's balance
				send "&aYou have received your first &e2000&a tickets for getting supporter ultimate! Enjoy!" to player
				set {ticket.tracker.bonus.%player%} to true
				stop
		{ticket.tracker.count.%player%} is not equal to {ticket.tracker.count}:
			set {_pay.%player%} to difference between {ticket.tracker.count} and {ticket.tracker.count.%player%}
			set {_pay.%player%} to 2000 * {_pay.%player%}
			add {_pay.%player%} to player's balance
			set {ticket.tracker.count.%player%} to {ticket.tracker.count}
			set {db_ticket.tracker.count.%player%} to {ticket.tracker.count.%player%}
			send "&aYou have received &e2000&a tickets for your weekly allowance! Enjoy!" to player


every 30 minutes:
	set {ticket.tracker.count} to {db_ticket.tracker.count}
	difference between {ticket.tracker} and now is greater than or equal to 7 days:
		set {ticket.tracker} to now
		{ticket.tracker.count} is not set:
			set {ticket.tracker.count} to 0
		add 1 to {ticket.tracker.count}
		set {db_ticket.tracker.count} to {ticket.tracker.count}
		
	loop all players:
		loop-player has permission "obam.supporter.tickets"
		{ticket.tracker.count.%loop-player%} is not equal to {ticket.tracker.count}:
			add 2000 to loop-player's balance
			add 1 to {ticket.tracker.count.%loop-player%}
			{ticket.tracker.count.%loop-player%} is not set:
				set {ticket.tracker.count.%loop-player%} to {ticket.tracker.count}
				set {db_ticket.tracker.count.%loop-player%} to {ticket.tracker.count.%loop-player%}
			send "&aYou have received &e2000&a tickets for your weekly allowance! Enjoy!" to loop-player

			
command /syncup:
	trigger:
		player is op
		set {db_ticket.tracker.count} to {ticket.tracker.count}
		set {db_ticket.tracker} to {ticket.tracker}
		
command /ticketcounterset <integer> [<player>]:
	trigger:
		player is op
		player-argument is not set:
			set {ticket.tracker.count} to argument 1
		player-argument is set:
			set {ticket.tracker.count.%player-argument%} to argument 1
		
command /syncdown:
	trigger:
		player is op
		set {ticket.tracker.count} to {db_ticket.tracker.count}
		set {ticket.tracker} to {db_ticket.tracker}	
			
			
command /addtoticket:
	trigger:
		player is op
		{ticket.tracker.count} is not set:
			set {ticket.tracker.count} to 0
		add 1 to {ticket.tracker.count}
		
command /viewtime:
	trigger:
		player is op
		send "%{ticket.tracker.count}%" to player
		send "%{ticket.tracker.count.%player%}%" to player
		
		
command /clearultimate <offline player>:
	trigger:
		player is op
		clear {ticket.tracker.count.%offline player-argument%}
		
command /updateplayers:
	trigger:
		player is op
		loop all players:
			loop-player has permission "obam.supporter.tickets":
				set {db_ticket.tracker.count.%loop-player%} to {ticket.tracker.count.%loop-player%}
		
		
			