command /msg [<player>] [<text>]:
	permission: obam.free
	aliases: @
	trigger:
		argument 1 is set:
			argument 1 is player:
				send "&cWhy would you talk to yourself? Are you crazy!?!?!" to player
				stop
			argument 2 is not set:
				send "&dYou have started a conversation with &e%argument 1%" to player
				set {message.%player%} to argument 1
			argument 2 is set:
				send "&d%player%&l ⇉ &r&d%argument 1%: %argument 2%" to argument 1
				send "&d%player%&l ⇉ &r&d%argument 1%: %argument 2%" to player
				set {reply.%argument 1%} to player
				
		argument 1 is not set:
			{message.%player%} is not set:
				send "&cYou are not in a private conversation!" to player
			{message.%player%} is set:
				send "&aYou have left your conversation." to player
				clear {message.%player%}
				
				
on chat:
	{message.%player%} is set:
		cancel event
		send "&d%player%&l ⇉ &r&d%{message.%player%}%: %message%" to {message.%player%}
		send "&d%player%&l ⇉ &r&d%{message.%player%}%: %message%" to player
		set {reply.%{message.%player%}%} to player
		
command /reply <text>:
	permission: obam.free
	aliases: /r, @@
	trigger:
		{reply.%player%} is not set:
			send "&cYou have no one to reply to!" to player
			stop
		argument 1 is not set:
			send "&cYou can not reply with nothing!"
			stop
		send "&d%player%&l ⇉ &r&d%{reply.%player%}%: %argument%" to {reply.%player%}
		send "&d%player%&l ⇉ &r&d%{reply.%player%}%: %argument%" to player
			
		