variables:
	{abstain.%player%} = false



command /abstain [<text>]:
	permission: obam.free
	trigger:
		
		argument is not set:
			send " "
			send " &aYour Abstain status is currently &e%{abstain.%player%}%&a, you can change this by doing &e/abstain confirm&a. "
			send " "
			send "&aThis change will cost &e2500 Tickets&a."
			send " "
			set {abst.confirm.%player%} to now
			stop
		player has permission "obam.admin":
			{abstain.%player%} is false:
				set {abstain.%player%} to true
			
				send "&aYour Abstain status is now &e%{abstain.%player%}%"
				stop
				
			{abstain.%player%} is true:
				set {abstain.%player%} to false
				send "&aYour Abstain status is now &e%{abstain.%player%}%"
				stop
			
			stop
			
		argument is "confirm" or "c":
			set {_hold} to difference between now and {abst.confirm.%player%}
			{_hold} is greater than 30 seconds:
				send "&cYou must do &e/abstain&a before doing the confirm command"
				stop
		
			{abstain.%player%} is not set:
				set {abstain.%player%} to false
			{abstain.%player%} is false:
				set {_bal} to player's balance
				{_bal} is less than 2500:
					send "&cYou do not have enough tickets to perform this operation"
					stop
				remove 2500 from player's balance
				set {abstain.%player%} to "wait abstain"
				set {abstain.%player%.time} to now
				send "&aYou have abstained from PvP. You will lose access to some features. You have paid a toll of &e2500 Tickets&a."
				send "&aIt can take up to &e2 hours&a for your abstain feature to take affect."
				send "&aYou know have &e%player's balance%&a."
				stop
			{abstain.%player%} is true:
				set {_bal} to player's balance
				{_bal} is less than 2500:
					send "&cYou do not have enough tickets to perform this operation"
					stop
				remove 2500 from player's balance
				set {abstain.%player%} to "wait pvp"
				set {abstain.%player%.time} to now
				send "&aYou are engaging in PvP. You will be susceptible to PvP fights. You have paid a toll of &e2500 Tickets&a."
				send "&aIt can take up to &e2 Hours&a for your PvP entering process to take affect."
				send "&aYou now have &e%player's balance%&a."
				stop
				
			{abstain.%player%} is "wait pvp":
				send "&cYou already have an Abstain process waiting. It can take up to 2 hours for this change to take an effect"
				stop
			{abstain.%player%} is "wait abstain":
				send "&cYou already have an Abstain process waiting. It can take up to 2 hours for this change to take an effect"
				stop
			
on damage:
	victim is a player
	attacker is a player
	{abstain.%victim%} is true:
		cancel event
	{abstain.%attacker%} is true:
		send "&cYou can not engage in PvP while abstaining!"
		cancel event
		
every 1 hour:
	loop all players:
		{abstain.%loop-player%} is "wait pvp":
			set {_hold} to difference between {abstain.%loop-player%.time} and now
			{_hold} is more than 1 hour
			set {abstain.%loop-player%} to false
			execute console command "perms player %loop-player% set nametags.color.blue false"
			execute console command "perms player %loop-player% set nametags.color.red"
			send "&aYou are now able to PvP!" to loop-player
		{abstain.%loop-player%} is "wait abstain":
			set {_hold} to difference between {abstain.%loop-player%.time} and now
			{_hold} is more than 1 hour
			set {abstain.%loop-player%} to true
			execute console command "perms player %loop-player% set nametags.color.red false"
			execute console command "perms player %loop-player% set nametags.color.blue"
			send "&aYou are now abstaining from PvP!" to loop-player
			
on connect:
	player is "ISMOOCH":
		stop
	{abstain.%player%} is true:
		player does not have permission "nametags.color.blue":
			execute console command "perms player %player% set nametags.color.blue"
		player has permission "nametags.color.red":
			execute console command "perms player %player% set nametags.color.red false"
	{abstain.%player%} is false:
		player does not have permission "nametags.color.red":
			execute console command "perms player %player% set nametags.color.red"
		player has permission "nametags.color.blue":
			execute console command "perms player %player% set nametags.color.blue false"
	{abstain.%player%} is "wait pvp":
		set {_hold} to difference between {abstain.%player%.time} and now
		{_hold} is more than 1 hour:
			set {abstain.%player%} to false
			send "&aYou can now PvP!"
			execute console command "perms player %player% set nametags.color.blue false"
			execute console command "perms player %player% set nametags.color.red"
			stop
			
	{abstain.%player%} is "wait abstain":
		set {_hold} to difference between {abstain.%player%.time} and now
		{_hold} is more than 1 hour:
			set {abstain.%player%} to true
			send "&aYou are now abstaining from PvP!"
			execute console command "perms player %player% set nametags.color.red false"
			execute console command "perms player %player% set nametags.color.blue"
			stop