variables:
	{group.%player%} = false


on chat:
	cancel event
#startfold @header-settings
	if player has permission "obam.admin":
		player is "ISMOOCH":
			set {_header} to "&d[DEV] %player%"
		set {_header} to "&d[ADMIN] %player%"
	{_header} is not set:
		if player has permission "obam.smod":
			set {_header} to "&2[MOD] %player%"
	{_header} is not set:
		if player has permission "obam.mod":
			set {_header} to "&2[MOD] %player%"
	{_header} is not set:
		if player has permission "obam.ultimate":
			set {_header} to "&6[^] %player%"
	{_header} is not set:
		if player has permission "obam.plus":
			set {_header} to "&b[+] %player%"
	{_header} is not set:
		if player has permission "obam.supporter":
			set {_header} to "&f%player%"
	{_header} is not set:
		set {_header} to "&f%player%"
#endfold
#startfold @channel-detection

	#subfold @friends
	{channel.%player%} is "group":
		{group.%player%} is true:
			set {_group.id} to {group.id.%player%}
			set {_group.owner} to {group.owner.%{_group.id}%}
				
			loop {group.%{_group.id}%.%{_group.owner}%::*}:
				set {_player} to loop-index parsed as player
				{group.%{_group.id}%.name} is set:
					send "&a[%{group.%{_group.id}%.name}%] <reset>%{_header}%&a: %message%" to {_player}
				else:
					send "%{_header}%&a: %message%" to {_player}
			stop
		else:
			clear {channel.%player%}
	
	#subfold @staff
	{channel.%player%} is "staff":
		player does not have permission "obam.mod":
			clear {channel.%player%}
			broadcast "%{_header}%&f: %message%"
			delete {channel.staff::%player%}
			stop
		loop {channel.staff::*}:
			send "%{_header}%&3: %message%" to loop-value
		stop
			
	#subfold @supporter
	{channel.%player%} is "supporter":
		player does not have permission "obam.supporter":
			clear {channel.%player%}
			broadcast "%{_header}%&f: %message%"
			delete {channel.supporter::%player%}
			stop
		loop {channel.supporter::*}:
			send "%{_header}%&e: %message%" to loop-value
		stop
	#subfold @main		
	broadcast "%{_header}%&f: %message%"
#endfold

#startfold @chatcommand
command /ch [<text>]:
	permission: obam.free
	trigger:
		argument 1 is not set:
			send "&aProper usage: &e/ch [Channel Name]" to player
			stop
			
			
		argument 1 is "m":
			player does not have permission "obam.mod":
				send "&cYou do not have permission to do this!" to player
				stop
			set {channel.%player%} to "staff"
			set {channel.staff::%player%} to player
			send "&aYou are now speaking in the &3Moderator&a channel!" to player
			stop
			
			
		argument 1 is "s":
			player does not have permission "obam.supporter":
				send "&cYou do not have permission to do this!" to player
				stop
			set {channel.%player%} to "supporter"
			set {channel.supporter::%player%} to player
			send "&aYou are now speaking in the &eSupporter&a channel!" to player
			stop
			
			
		argument 1 is "t":
			{group.%player%} is not true:
				send "&cYou must be in a Team to do this!" to player
				stop
			set {channel.%player%} to "group"
			send "&aYou are now speaking in the &a&lTeam&a channel!" to player
			stop
			
			
		argument 1 is "g":
			clear {channel.%player%}
			send "&aYou are now speaking in the &fGlobal&a channel!"
#endfold

on join:
	player does not have permission "obam.mod":
		delete {channel.staff::%player%}
	player does not have permission "obam.supporter":
		delete {channel.supporter::%player%}
	clear {channel.%player%}
#endfold