options:
	p: &c[W]<reset>
	


on join:
	{db_global.%player%} is not set:
		set {db_global.%player%} to true
	{db_global.%player%} is true:
		set {db_channel.global::%player%} to player
		set {db_channel.%player%} to "global"
	player does not have permission "obam.supporter":
		delete {db_channel.supporter::%player%}
	player does not have permission "obam.mod":
		delete {db_channel.supporter::%player%}
	{db_channel.sup.%player%} is not set:
		player has permission "obam.supporter"
		set {db_channel.sup.%player%} to true
	{db_channel.sup.%player%} is true:
		set {db_channel.supporter::%player%} to player
	{db_channel.staff.%player%} is not set:
		player has permission "obam.mod"
		set {db_channel.staff.%player%} to player
	{db_channel.staff.%player%} is true:
		set {db_channel.supporter::%player%} to player
		
on chat:
	cancel event
	player is "IcecreamCow" or "Electric_Hamster" or "ISMOOCH":
		
		set {_pre} to "{@p} &d[A] %player%"
	{_pre} is not set:
		player has permission "obam.mod":
			set {_pre} to "{@p} &2[M] %player%"
	{_pre} is not set:
		player has permission "obam.ultimate":
			set {_pre} to "{@p} &6[^] %player%"
	{_pre} is not set:
		player has permission "obam.plus":
			set {_pre} to "{@p} &b[+] %player%"
	{_pre} is not set:
		set {_pre} to "{@p} %player%"
	player is "BruSwain":
		set {_pre} to "{@p} &6[^] %player%"
		
	{db_channel.%player%} is "staff":
		player does not have permission "obam.mod":
			set {db_channel.%player%} to "global"
			delete {db_channel.staff::%player%}
		{db_channel.%player%} is "staff":
			loop {db_channel.staff::*}:
				clear {_player}
				
				set {_player} to loop-index parsed as player
				set message to "&2%message%"
				set {_message} to "%{_pre}%&2: %message%"
				
				send "%{_message}%" to {_player}
			
		execute console command "/modpush %{_pre}%&2: %message%"
		
				
	{db_channel.%player%} is "supporter":
		player does not have permission "obam.supporter":
			set {db_channel.%player%} to "global"
			delete {db_channel.supporter::%player%}
		{db_channel.%player%} is "supporter":
			loop {db_channel.supporter::*}:
				clear {_player}
				set {_player} to loop-index parsed as player
				set message to "&b%message%"
				set {_message} to "%{_pre}%&b: %message%"
				
				send "%{_message}%" to {_player}
				
			execute console command "/supporterpush %{_message}%"
				
			
			stop
				
	{db_channel.%player%} is "global":
		loop {db_channel.global::*}:
			clear {_player}
			set {_player} to loop-index parsed as player
		
			send "%{_pre}%&f: %message%" to {_player}

			
		execute console command "globalpush %{_pre}%&f: %message%"
		
		stop
			
			

		
command /chat [<text>] [<text>]:
	permission: obam.free
	aliases: c, ch
	trigger:
		
		argument 1 is "m" or "mod":
			player does not have permission "obam.mod":
				send "&cYou dont have permission to do this!"
				stop
			set {db_channel.%player%} to "staff"
			send "&aYou are now chatting in the &2Mod&a channel!"
			stop
		argument 1 is "s" or "supporter":
			player does not have permission "obam.supporter":
				send "&cYou dont have permission to do this!"
				stop
			set {db_channel.%player%} to "supporter"
			send "&aYou are now chatting in the &bSupporter&a channel!"
		
		argument 1 is "g" or "global":
			set {db_channel.%player%} to "global"
			send "&aYou are now chatting in the &fGlobal&a channel!"
			
		argument 1 is "l" or "leave":
			argument 2 is not set:
				send "&cPlease specify a channel: &e/chat leave <channel>"
				stop
			argument 2 is "mod" or "m":
				send "&cYou can not leave the staff chat silly"
				stop
			argument 2 is "s" or "supporter":
				send "&cYou are now leaving the &bSupporter&c chat!"
				delete {db_channel.supporter::%player%}
				stop
			argument 2 is "g" or "global":
				send "&cYou are now leaving the &fGlobal&c chat!"
				delete {db_channel.global::%player%}
				stop
		argument 1 is "j" or "join":
			argument 2 is not set:
				send "&cPlease specify a channel: &e/chat join <channel>"
				stop
			argument 2 is "mod" or "m":
				player does not have permission "obam.mod":
					send "&cYou do not have permission to do this!"
					stop
				{db_channel.staff::%player%} is set:
					send "&cYou are already in this channel!"
					send "&cIf you believe this is an error, please report it!"
					stop
				set {db_channel.staff::%player%} to player
				set {db_channel.%player%} to "staff"
				send "&aYou are now in the &2Mod&a channel!"
				stop
			
			argument 2 is "s" or "supporter":
				player does not have permission "obam.supporter":
					send "&cYou do not have permission to do this!"
					stop
				{db_channel.supporter::%player%} is set:
					send "&cYou are already in this channel!"
					send "&cIf you believe this is an error, please report it!"
					stop
				set {db_channel.supporter::%player%} to player
				set {db_channel.%player%} to "supporter"
				send "&aYou are now in the &bSupporter&a channel!"
				stop
				
			argument 2 is "g" or "global":
				{db_channel.global::%player%} is set:
					send "&cYou are already in this channel!"
					send "&cIf you believe this is an error, please report it!"
					stop
				set {db_channel.global::%player%} to player
				set {db_channel.%player%} to "global"
				send "&aYou are now in the &fGlobal&a channel!"
				
		argument 1 is "who":
			argument 2 is not set:
				loop {db_channel.%{db_channel.%player%}%::*}:
					send "%loop-index%"
					


	
	
		
				
		
		
			
	