

		
	
command /globalpush <text>:
	permission: obam.admin
	trigger:
		forward command "globalcatch %argument%" to console
command /globalcatch <text>:
	permission: obam.admin
	trigger:
		
		loop {db_channel.global::*}:
			clear {_player}
			set {_player} to loop-index parsed as player
			set {_message} to "&f%argument%"
			{_message} contains "%{_player}%":
				replace "%{_player}%" in {_message} with "&c%{_player}%&f"
				{db_alerts.on.%{_player}%} is true:
					play level up at location of {_player} with pitch 2

				

			send "%{_message}%" to {_player}
				
		stop
		
command /modpush <text>:
	permission: obam.admin
	trigger:
		forward command "modcatch %argument%" to console
		
command /modcatch <text>:
	permission: obam.admin
	trigger:
		
		loop {db_channel.staff::*}:
			clear {_player}
			set {_player} to loop-index parsed as player
			set {_message} to "&a%argument%"
			{_message} contains "%{_player}%":
				replace "%{_player}%" in {_message} with "&c%{_player}%&a"
				{db_alerts.on.%{_player}%} is true:
					play level up at location of {_player} with pitch 2

				

			send "%{_message}%" to {_player}
			
		stop
		
command /supporterpush <text>:
	permission: obam.admin
	trigger:
		forward command "supportercatch %argument%" to console
		
command /supportercatch <text>:
	permission: obam.admin
	trigger:
		loop {db_channel.supporter::*}:
			clear {_player}
			set {_player} to loop-index parsed as player
			set {_message} to "&b%argument%"
			{_message} contains "%{_player}%":
				replace "%{_player}%" in {_message} with "&c%{_player}%&b"
				{db_alerts.on.%{_player}%} is true:
					play level up at location of {_player} with pitch 2

				

			send "%{_message}%" to {_player}
			
command /mechpush <text>:
	permission: obam.admin
	trigger:
		forward command "mechcatch %argument%" to console
		
command /mechcatch <text>:
	permission: obam.admin
	trigger:
		loop {db_channel.mech::*}:
			clear {_player}
			set {_player} to loop-index parsed as player
			set {_message} to "&e%argument%"
			{_message} contains "%{_player}%":
				replace "%{_player}%" in {_message} with "&c%{_player}%&e"
				{db_alerts.on.%{_player}%} is true:
					play level up at location of {_player} with pitch 2

				

			send "%{_message}%" to {_player}
			
command /privatepush <text> <text>:
	permission: obam.admin
	trigger:
		forward command "privatecatch %argument 1% %argument 2%" to console

			
command /privatecatch <text> <text>:
	permission: obam.admin
	trigger:
		loop all players:
			"%loop-player%" is argument 1
			send argument 2 to loop-player
			{db_alerts.on.%loop-player%} is true:
				play level up at location of loop-player with pitch 2
			stop
			
command /fishcatch <text> <text>:
	permission: obam.admin
	trigger:
		loop all players:
			"%loop-player%" is argument 1
			{db_alerts.on.%loop-player%} is true
			play slime attack at location of loop-player with pitch 1
			send "&e%argument 2% &ajust slapped you with a giant fish!" to loop-player
			stop