

on script load:
	clear {tma.spawns::*}
	add creeper to {tma.spawns::*}
	add witch to {tma.spawns::*}
	add zombie to {tma.spawns::*}
	add skeleton to {tma.spawns::*}
	add zombie pigman to {tma.spawns::*}
	add cave spider to {tma.spawns::*}
	add magma cube to {tma.spawns::*}
	add blaze to {tma.spawns::*}



command /tma [<text>] [<text>] [<text>]:
	permission: obam.admin
	trigger:
		world is not "TMA":
			send "&cYou are not in the right world to do this"
			stop
	
		argument 1 is not set:
		
			send "&a================================="
			send "&6            OBAMCraft            "
			send "&6              TMA         "
			send "&a================================="
			send " "
			send "&e/tma addspawn <team>"
			send "&7Add your current location to the spawn list for that team"
			send " "
			send "&e/tma listspawn <team>"
			send "&7List the current spawn locations for a specified team"
			send " "
			send "&e/tma delspawn <number>"
			send "&7Deleted specified spawn location"
			send " "
			send "&e/tma addteam <team>"
			send "&7Add a team to the list of teams"
			send " "
			send "&e/tma listteam"
			send "&7List the current teams"
			send " "
			send "&e/tma delteam <team>"
			send "&7Delete the selected team from the team list"
			send " "
			send "&6Developed for &7OBAMCraft &eBy: &aThe OBAM Mechanics"
			stop
			
		argument 1 is "help":
			argument 2 is not set:
		
				send "&a================================="
				send "&6            OBAMCraft            "
				send "&6              TMA         "
				send "&a================================="
				send " "
				send "&e/tma addspawn <team>"
				send "&7Add your current location to the spawn list for that team"
				send " "
				send "&e/tma listspawn <team>"
				send "&7List the current spawn locations for a specified team"
				send " "
				send "&e/tma delspawn <number>"
				send "&7Deleted specified spawn location"
				send " "
				send "&e/tma addteam <team>"
				send "&7Add a team to the list of teams"
				send " "
				send "&e/tma listteam"
				send "&7List the current teams"
				send " "
				send "&e/tma delteam <team>"
				send "&7Delete the selected team from the team list"
				send " "
				send "&6Developed for &7OBAMCraft &eBy: &aThe OBAM Mechanics"
				stop
			argument 2 is "1":
				send "&a================================="
				send "&6            OBAMCraft            "
				send "&6              TMA         "
				send "&a================================="
				send " "
				send "&e/tma addspawn <team>"
				send "&7Add your current location to the spawn list for that team"
				send " "
				send "&e/tma listspawn <team>"
				send "&7List the current spawn locations for a specified team"
				send " "
				send "&e/tma delspawn <number>"
				send "&7Deleted specified spawn location"
				send " "
				send "&e/tma addteam <team>"
				send "&7Add a team to the list of teams"
				send " "
				send "&e/tma listteam"
				send "&7List the current teams"
				send " "
				send "&e/tma delteam <team>"
				send "&7Delete the selected team from the team list"
				send " "
				send "&6Developed for &7OBAMCraft &eBy: &aThe OBAM Mechanics"
				stop
				
			argument 2 is "2":
				send "&a================================="
				send "&6            OBAMCraft            "
				send "&6              TMA         "
				send "&a================================="
				send " "
				send "&e/tma spawnwave <number>"
				send "&7Spawns a wave, at wave number listed"
				send " "
				send "&e/tma help <number>"
				send "&7List this help menu at specified page number"
				send " "
				send "&e/tma begin"
				send "&7Begin a TMA game(not live yet)"
				send " "
				send "&e/tma activeadd <team>"
				send "&7Add a team to the active list"
				send " "
				send "&e/tma activelist"
				send "&7List all active teams"
				send " "
				send "&e/tma activedel <team>"
				send "&7Remove a team from the active list"
				send " "
				send "&6Developed for &7OBAMCraft &eBy: &aThe OBAM Mechanics"
				stop
		
		
		argument 1 is "addspawn":
			argument 2 is not set:
				send "&cYou must select a team: &e/tma addspawn <team>"
				stop
			{tma.teams::%argument 2%} is not set:
				send "&cThis is not a valid team!"
				send "&cPlease do &e/tma teamlist&c for a list of available teams."
				stop
			add location of player to {tma.%argument 2%.spawn::*}
			send "&e%location of player% &a is added to &e%argument 2%'s&a spawn list"
		
		argument 1 is "listspawn":
			argument 2 is not set:
				send "&cYou must select a team: &e/tma listspawn <team>"
				stop
			{tma.teams::%argument 2%} is not set:
				send "&cThis is not a valid team!"
				send "&cPlease do &e/tma teamlist&c for a list of available teams."
			loop {tma.%argument 2%.spawn::*}:
				{_loop.count} is not set:
					set {_loop.count} to 0
				add 1 to {_loop.count}
				send "%loop-index%.....%loop-value%"
				
		argument 1 is "delspawn":
			argument 2 is not set:
				send "&cYou must select a team: &e/tma delspawn <team> <number>"
				stop
			argument 3 is not set:
				send "&cYou must select a point: &e/tma delspawn %argument 2% <number>"
				stop
			{tma.teams::%argument 2%} is not set:
				send "&cThis is not a valid team!"
				send "&cPlease do &e/tma teamlist&c for a list of available teams."
			{tma.%argument 2%.spawn::%argument 3%} is not set:
				send "&c%argument 3% is not a point in team %argument 2%"
				send "&cPlease use &e/tma listspawn %argument 2%&a to find the available points"
				stop
		
			send "&cDeleteing &e%{tma.%argument 2%.spawn::%argument 3%}% &ain &e%argument 2%&a..."
			delete {tma.%argument 2%.spawn::%argument 3%}
			{tma.%argument 2%.spawn::%argument 3%} is set:
				send "&cAn error occurred"
				stop
			send "&aDeleted!"
			
		argument 1 is "addteam":
			argument 2 is not set:
				send "&cPlease specify a team: &e/tma addteam <team>"
				stop
			set {tma.teams::%argument 2%} to true
			send "&e%argument 2%&a added successfully to Teams!"
			
		argument 1 is "listteam":
			loop {tma.teams::*}:
				send "%loop-index%"
				
		argument 1 is "delteam":
			argument 2 is not set:
				send "&cPlease specify a team: &e/tma delteam <team>"
				stop
			{tma.teams::%argument 2%} is not set:
				send "&cThis team does not exist!"
				send "&cPlease use &e/tma listteam&a for a list of teams"
				stop
			
			send "&cDeleteing &e%argument 2%&c..."
			delete {tma.teams::%argument 2%}
			{tma.teams::%argument 2%} is set:
				send "&cAn error occurred"
				stop
			send "&aDelted!"
			
		argument 1 is "spawnwave":
			argument 2 is not set:
				send "&cPlease select a number: &e/tma spawnwave <number>"
				stop
			{active.tma.teams::*} is empty:
				send "&cThere are no active teams: &e/tma activeadd <team>&c to add"
				stop
			execute console command "tmawave %argument 2%"
			
		argument 1 is "activeadd":
			argument 2 is not set:
				send "&cPlease select a team: &e/tma activeadd <team>"
				stop
			{tma.teams::%argument 2%} is not set:
				send "&cThis team does not exist!"
				send "&cPlease use &e/tma listteam&a for a list of teams"
				stop
			{tma.%argument 2%.spawn::*} is empty:
				send "&cThere are no spawn points set for this team!"
				send "&cPlease use &e/tma spawnadd %argument 2%&c to add spawn points!"
				stop
			set {active.tma.teams::%argument 2%} to true
			send "&e%argument 2%&a added to active teams list"
			
		argument 1 is "activedel":
			argument 2 is not set:
				send "&cPlease select a team: &e/tma activedel <team>"
				stop
			{active.tma.teams::%argument 2%} is not set:
				send "&cTeam is not listed as active!"
				send "&cPlease use &e/tma activelist &cfor a list of active teams!"
				stop
			send "&cDeleting &e%argument 2%&c from active teams..."
			delete {active.tma.teams::%argument 2%}
			{active.tma.teams::%argument 2%} is set:
				send "&cAn error occurred!" 
				stop
			send "&aDelete Successful!"
			
		argument 1 is "activelist":
			{active.tma.teams::*} is empty:
				send "&cThere are no active teams!"
				send "&cUse &e/tma activeadd <team>&c to add active teams"
				stop
			loop {active.tma.teams::*}:
				send "%loop-index%"
				
			
			
command /tmawave [<text>]:
	permission: obam.admin
	trigger:
		send "&aIama message"
		{active.tma.teams::*} is empty:
			send "&cError"
			stop
		argument 1 is not set:
			send "&cError!"
			stop
		send "&aI ama another message"
		set {_num} to argument 1 parsed as number
		send "&a%{_num}%"
		{_num} is less than 5:
			set {_loop} to {_num} * 2 + 1
		
		{_num} is greater than 5:
			set {_loop} to {_num} * 2 + 3
		
		send "&a%{_loop}%"
		set {_size} to size of {active.tma.teams::*}
		send "&a%{_size}%"
		set {_count} to 1
		send "%{_count}%"
		while {_count} is less than or equal to {_size}:
			{_count} is not set:
				set {_count} to 1
			loop {active.tma.teams::*}:
	
				send "&a%loop-index%"
				loop {_loop} times:
					set {_ran} to random element of {tma.spawns::*}
					set {_loc} to random element of {tma.%loop-index-1%.spawn::*}
					spawn {_ran} at {_loc}
					set {_cur.entity} to spawned entity
					spawned entity is zombie:
							
						equip spawned entity with iron helmet
						chance of 5%:
							apply speed 2 to spawned entity for 999 days
						chance of 10%:
							equip spawned entity with iron helmet of unbreaking 2
									
						chance of 15%:
							set spawned entity's tool to iron sword
							chance of 5%:
								set spawned entity's tool to iron sword of sharpness 2
								chance of 5%:
									set spawned entity's tool to diamond sword
											
					spawned entity is skeleton:
						
						equip spawned entity with leather helmet
								
						set spawned entity's tool to bow
						chance of 5%:
							apply speed 2 to spawned entity for 999 days
						chance of 10%:
							equip spawned entity with iron helmet of unbreaking 2
						chance of 15%:
							set spawned entity's tool to bow of punch 1
							chance of 5%:
								equip spawned entity with diamond chestplate
							chance of 2%:
								equip spawned entity with diamond leggings of projectile protection 1
											
					spawned entity is a creeper:
								
						chance of 5%:
							apply speed 2 to spawned entity for 999 days
									
					spawned entity is cave spider:
								
						chance of 5%:
							apply speed to spawned entity for 999 days
								
					spawned entity is zombie pigman:
								
						set spawned entity's tool to gold sword
						chance of 5%:
							apply speed to spawned entity for 999 days
				
					
				
			
			add 1 to {_count}

	
				
				
		
				
			
			
	