on place:
	event-block is named:
		set {placed.things.named::%event-block%} to name of event-block
		add event-block to {placed.things::*}
	
on break:
	loop {placed.things::*}:
		event-block is {placed.things::%loop-index%}
		cancel event
		delete event-block
		set {_block} to {placed.things::%loop-index%}
		drop {placed.things::%loop-index%} at event-location
		name spawned item "%{placed.things.named::%{_block}%}%"
		delete {placed.things::%loop-index%}