command /effect [<number>] [<number=1>] [<number=1>]:
	permission: obam.admin
	trigger:
		
		argument 1 is not set:
			send "1  ... hugeexplosion"
			send "2  ... largeexplode"
			send "3  ... bubble"
			send "4  ... suspended"
			send "5  ... depthsuspend"
			send "6  ... townaura"
			send "7  ... crit"
			send "8  ... magicCrit"
			send "9  ... smoke"
			send "10 ... mobSpell"
			send "11 ... mobSpellAmbient"
			send "12 ... instantSpellAmbient"
			send "13 ... witchMagic"
			send "14 ... note"
			send "15 ... portal"
			send "16 ... enchantmenttable"
			send "17 ... explode"
			send "18 ... flame"
			send "19 ... lava"
			send "20 ... footstep"
			send "21 ... splash"
			send "22 ... largesmoke"
			send "23 ... cloud"
			send "24 ... reddust"
			send "25 ... snowballpoof"
			send "26 ... dripWater"
			send "27 ... dripLava"
			send "28 ... snowshovel"
			send "29 ... slime"
			send "30 ... heart"
			send "31 ... angryVillager"
			send "32 ... happyVillager"
			send "33 ... redust?"
		
		argument 1 is set:
			argument 1 is 1:
				set {_effect} to "hugeexplosion"
			argument 1 is 2:
				set {_effect} to "largeexplod"
			argument 1 is 3:
				set {_effect} to "bubble"
			argument 1 is 4:
				set {_effect} to "suspended"
			argument 1 is 5:
				set {_effect} to "depthsuspend"
			argument 1 is 6:
				set {_effect} to "townaura"
			argument 1 is 7:
				set {_effect} to "crit"
			argument 1 is 8:
				set {_effect} to "magicCrit"
			argument 1 is 9:
				set {_effect} to "smoke"
			argument 1 is 10:
				set {_effect} to "mobSpell"
			argument 1 is 11:
				set {_effect} to "mobSpellAmbient"
			argument 1 is 12:
				set {_effect} to "isntantSpellAmbient"
			argument 1 is 13:
				set {_effect} to "witchMagic"
			argument 1 is 14:
				set {_effect} to "note"
			argument 1 is 15:
				set {_effect} to "portal"
			argument 1 is 16:
				set {_effect} to "enchantmenttable"
			argument 1 is 17:
				set {_effect} to "explode"
			argument 1 is 18:
				set {_effect} to "flame"
			argument 1 is 19:
				set {_effect} to "lava"
			argument 1 is 20:
				set {_effect} to "footstep"
			argument 1 is 21:
				set {_effect} to "splash"
			argument 1 is 22:
				set {_effect} to "largesmoke"
			argument 1 is 23:
				set {_effect} to "cloud"
			argument 1 is 24:
				set {_effect} to "reddust"
			argument 1 is 25:
				set {_effect} to "snowballpoof"
			argument 1 is 26:
				set {_effect} to "dripWater"
			argument 1 is 27:
				set {_effect} to "dripLava"
			argument 1 is 28:
				set {_effect} to "snowshovel"
			argument 1 is 29:
				set {_effect} to "slime"
			argument 1 is 30:
				set {_effect} to "heart"
			argument 1 is 31:
				set {_effect} to "angryVillager"
			argument 1 is 32:
				set {_effect} to "happyVillager"
			argument 1 is 33:
				set {_loc} to block above player's head
				play argument 2 of effect "blockcrack_152_0" with data argument 3 at location of player
				stop
				
			set {_location} to block above player
				
			play argument 2 of effect {_effect} with data argument 3 at {_location}
			
command /lighton:
	permission: obam.admin
	trigger:
		{light.%player%} is not set:
			set {light.%player%} to false
		{light.%player%} is false:
			set {light.%player%} to true
			send "&aLights on"
			stop
		{light.%player%} is true:
			set {light.%player%} to false
			send "&cLights off"
			make player see {light.%player%.lastblock} as {light.%player%.lastblock}
			clear {light.%player%.lastblock}
			loop {light.%player%::*}:
				make player see loop-value as loop-value
			stop
		
every 3 seconds:
	loop all players:
		{light.%loop-player%} is true:
			set {_loc} to location of player
			make loop-player see block below loop-player as torch
			wait 2.8 seconds
			make loop-player see block below loop-player as torch